# image will be published to ghcr.io/<user>/<name>
name: os-satellite
# description will be included in the image's metadata
description: blue-build image for my laptop

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: fonts
    fonts:
      nerd-fonts:
      # don't add "Nerd Font" suffix.
      - FiraCode
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
      google-fonts:
      - Roboto
      - Open Sans

  - type: dnf
    repos:
      cleanup: false
      copr:
      - atim/starship
      - alternateved/eza
      - monkeygold/nautilus-open-any-terminal
    install:
      packages:
        # terminal stuff
        - starship
        - fish
        - keychain
        - tmux
        - eza
        - nautilus-open-any-terminal
      # sshfs
        - fuse-sshfs
      # misc
        - gnome-tweaks
        - weechat
        - wl-clipboard
        - opendoas
        - tuned
    remove:
      packages:
        - firefox # default firefox removed in favor of flatpak
        - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
    group-install:
      packages:
        - virtualization
        
  - type: gnome-extensions
    install:
      - Just Perfection # https://extensions.gnome.org/extension/3843/just-perfection/
      - AppIndicator and KStatusNotifierItem Support # https://extensions.gnome.org/extension/615/appindicator-support/
      - Gnome 4x UI Improvements # https://extensions.gnome.org/extension/4158/gnome-40-ui-improvements/

  - type: script
    scripts:
      - font-maplemono.nu

  - type: default-flatpaks
    configurations:
    - notify: false
      scope: user
      repo:
        url: https://dl.flathub.org/repo/flathub.flatpakrepo
        name: flathub
        title: "Flathub" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      - org.mozilla.firefox
      - org.libreoffice.LibreOffice
      - com.borgbase.Vorta
      - org.gustavoperedo.FontDownloader
      - com.github.tchx84.Flatseal
      - com.calibre_ebook.calibre
      - com.github.Eloston.UngoogledChromium
      - com.spotify.Client
      - org.gimp.GIMP
      - org.gtk.Gtk3theme.Adwaita-dark
      - eu.betterbird.Betterbird
      - ca.desrt.dconf-editor
      - com.mattjakeman.ExtensionManager
      - io.mpv.Mpv
      - org.darktable.Darktable
      - app.devsuite.Ptyxis
      - io.github.swordpuffin.rewaita
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

