# image will be published to ghcr.io/<user>/<name>
name: os-satellite
# description will be included in the image's metadata
description: blue-build image for my laptop

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: fonts
    fonts:
      nerd-fonts:
      # don't add "Nerd Font" suffix.
      - FiraCode
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
      google-fonts:
      - Roboto
      - Open Sans
      
#  - type: bling
#    install:
#      - ublue-update

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/alternateved/eza/repo/fedora-%OS_VERSION%/alternateved-eza-fedora-%OS_VERSION%.repo
    install:
      - starship
      - fish
      - keychain
      - tmux
      - virt-manager
      - weechat
      - wl-clipboard
      - eza
      - opendoas
      - tuned
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    configurations:
    - notify: false
      scope: user
      repo:
        url: https://dl.flathub.org/repo/flathub.flatpakrepo
        name: flathub
        title: "Flathub" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      - org.mozilla.firefox # Firefox
      - org.libreoffice.LibreOffice # LibreOffice
      - com.borgbase.Vorta # Vorta
      - org.gustavoperedo.FontDownloader # FontDownloader
      - com.github.tchx84.Flatseal # Flatseal
      - com.calibre_ebook.calibre # Calibre
      - com.github.Eloston.UngoogledChromium # Ungoogled-Chromium
      - com.spotify.Client # Spotify
      - org.gimp.GIMP # GIMP
      - org.gtk.Gtk3theme.Adwaita-dark # Adwaita-dark
      - eu.betterbird.Betterbird # Betterbird
      - ca.desrt.dconf-editor # dconf-editor
      - com.mattjakeman.ExtensionManager # ExtensionManager
      - io.mpv.Mpv # mpv
      - org.darktable.Darktable # darktable
      - app.devsuite.Ptyxis # ptyxis
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

